<h3>Numpy Basic(Numeric Python) </h3>

In [1]:
#1)numpy as vector and matrix
#2)arange
#3)zeros
#4)ones
#5)linspace(linearely spaced)
#6)eye >> identity matrix
#7)random number generation
#8)reshape, dtype
#9)min, max and index of them
#10)math operations
#11)np slicing
#12)np broadcasting
#13)copy
#14)2d array indexing
#15)

In [2]:
import numpy as np

In [3]:
np.arange(-20, 3, 3)

array([-20, -17, -14, -11,  -8,  -5,  -2,   1])

In [4]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [5]:
np.zeros((1, 10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [6]:
np.zeros((1, 10)).dtype;np.zeros((1, 10)).shape

(1, 10)

In [7]:
np.zeros(10).dtype;np.zeros(10).shape

(10,)

In [8]:
np.ones((4,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [9]:
np.ones((2))

array([ 1.,  1.])

In [10]:
np.linspace(-5, 5, 10)

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

In [11]:
np.eye(3) #(rows, columns, k=index)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [12]:
np.random.rand(3,3) #uniform distribution

array([[ 0.40804399,  0.77402438,  0.97400734],
       [ 0.00279629,  0.75204062,  0.45946572],
       [ 0.95166708,  0.79895627,  0.10324367]])

In [13]:
np.random.randint(1,10,5) #discrete uniform distribution

array([1, 5, 5, 2, 3])

In [14]:
np.random.randn(3,3) #standard normal distribution.

array([[ 0.39795484, -0.30012945,  0.22815688],
       [ 0.38782882, -0.34018957, -1.58716064],
       [-1.08241075, -0.22988512, -0.73681108]])

In [15]:
rn = np.random.randn(3,3)
ri = np.random.randint(1,10,9)

In [16]:
rn

array([[ 0.50619186,  1.89337259,  1.36078406],
       [ 0.1697495 ,  0.68196326,  1.2087272 ],
       [-1.47518186, -1.63477215, -0.10787905]])

In [17]:
ri

array([9, 4, 7, 7, 6, 8, 4, 6, 7])

In [18]:
ri.reshape((3,3))

array([[9, 4, 7],
       [7, 6, 8],
       [4, 6, 7]])

In [19]:
ri.max()

9

In [20]:
ri.argmax()

0

In [21]:
ri.min()

4

In [22]:
ri.argmin()

1

<h3>Numpy Operations</h3>

In [24]:
arr=np.arange(0,10)

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr + arr #index to index additon and all arithmatic ops

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [29]:
np.log(arr) #gives you warning about math erros

C:\Users\DELL\Anaconda3\envs\pyfinance\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458])

In [34]:
arr = np.random.randint(10, 100, 10)

In [35]:
print(arr)
print(arr[:5])
print(arr[2:5])

[12 32 54 86 38 65 59 58 94 19]
[12 32 54 86 38]
[54 86 38]


In [37]:
print(arr)
#array broadcasting this cant be done in list
arr[:5] = 10
print(arr)

[12 32 54 86 38 65 59 58 94 19]
[10 10 10 10 10 65 59 58 94 19]


In [47]:
#must say copy or changes will happen in original array
ar = np.arange(1, 100, 10)
ar

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [48]:
print("origial array")
print(ar)
slic = ar[:5]
print(slic)
slic[:] = -5
print(slic)
print("origial array")
print(ar)

origial array
[ 1 11 21 31 41 51 61 71 81 91]
[ 1 11 21 31 41]
[-5 -5 -5 -5 -5]
origial array
[-5 -5 -5 -5 -5 51 61 71 81 91]


In [50]:
ar= np.arange(1, 100, 10)
print("origial array")
print(ar)
print("made copy of original")
slic = ar[:5].copy()
print(slic)
slic[:] = -5
print(slic)
print("origial array")
print(ar)

origial array
[ 1 11 21 31 41 51 61 71 81 91]
made copy of original
[ 1 11 21 31 41]
[-5 -5 -5 -5 -5]
origial array
[ 1 11 21 31 41 51 61 71 81 91]


In [54]:
mat = np.array([np.random.randint(1,5,3),np.random.randint(10,25,3),np.random.randint(30,50,3)])
mat

array([[ 3,  1,  1],
       [17, 22, 12],
       [32, 42, 38]])

In [55]:
mat[:]

array([[ 3,  1,  1],
       [17, 22, 12],
       [32, 42, 38]])

In [57]:
mat[:2, :2]

array([[ 3,  1],
       [17, 22]])

In [58]:
mat[1, -1:]

array([12])

In [59]:
mat[1,2]

12

<h5>Conditional Formating</h5>

In [60]:
mat[mat>4]

array([17, 22, 12, 32, 42, 38])