In [2]:
import numpy as np

In [3]:
np.ones((3, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [4]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [5]:
np.full((2,2), 24)

array([[24, 24],
       [24, 24]])

In [6]:
np.random.randint(10,99, (3,3))

array([[11, 19, 91],
       [51, 25, 41],
       [62, 95, 62]])

In [7]:
np.random.normal(0, 1, (3,3))
len(np.arange(2, 20,3))

6

In [8]:
np.array([[i for i in range(2,20,2)], [j for j in range(0,9,1)]],dtype=float)

array([[ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.]])

In [9]:
np.empty((2,2))

array([[0., 0.],
       [0., 0.]])

In [10]:
np.indices((2,3))

array([[[0, 0, 0],
        [1, 1, 1]],

       [[0, 1, 2],
        [0, 1, 2]]])

In [11]:
np.arange(2, 20,2).reshape(3,3)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [13]:
x = np.zeros((3,3), dtype=[('a', np.int32), ('b', np.float64, (3,3))])
x

array([[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])],
       [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])],
       [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]]),
        (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]],
      dtype=[('a', '<i4'), ('b', '<f8', (3, 3))])

In [14]:
x['a']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
x['b']

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [17]:
y = np.ones((3,3),dtype=[('a', np.int64), ('b', np.float64, (3,3))])
y

array([[(1, [[1., 1., 1.], [1., 1., 1.], [1., 1., 1.]]),
        (1, [[1., 1., 1.], [1., 1., 1.], [1., 1., 1.]]),
        (1, [[1., 1., 1.], [1., 1., 1.], [1., 1., 1.]])],
       [(1, [[1., 1., 1.], [1., 1., 1.], [1., 1., 1.]]),
        (1, [[1., 1., 1.], [1., 1., 1.], [1., 1., 1.]]),
        (1, [[1., 1., 1.], [1., 1., 1.], [1., 1., 1.]])],
       [(1, [[1., 1., 1.], [1., 1., 1.], [1., 1., 1.]]),
        (1, [[1., 1., 1.], [1., 1., 1.], [1., 1., 1.]]),
        (1, [[1., 1., 1.], [1., 1., 1.], [1., 1., 1.]])]],
      dtype=[('a', '<i8'), ('b', '<f8', (3, 3))])

In [21]:
x =np.array([[2, 3, 6],[4, 6, 9],[6, 8, 10]])
x.shape

(3, 3)

In [22]:
y = np.arange(2,20,2).reshape(3,3)

In [23]:
np.add(x, y)

array([[ 4,  7, 12],
       [12, 16, 21],
       [20, 24, 28]])

In [24]:
np.sum(y)

90

In [25]:
np.sum(y, axis=0)

array([24, 30, 36])

In [26]:
x

array([[ 2,  3,  6],
       [ 4,  6,  9],
       [ 6,  8, 10]])

In [27]:
x.transpose()

array([[ 2,  4,  6],
       [ 3,  6,  8],
       [ 6,  9, 10]])

In [31]:
x.trace()

18

In [32]:
y

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [33]:
v = np.array([1,1,1])

In [50]:
z = np.arange(30,56,3).reshape(3,3)
z

array([[30, 33, 36],
       [39, 42, 45],
       [48, 51, 54]])

In [56]:
a = np.add(y,np.ones((3,3), dtype=int))
a

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [58]:
z + v

array([[31, 34, 37],
       [40, 43, 46],
       [49, 52, 55]])